### ISSUE TITLE
Can't update/signin, Error "Binusmaya server is action weird"

### ISSUE THREAD

**Issue by chrsep** [chrsep/Kingfish#25]
There is a change in how binusmaya logs in. Now a call to https://binusmaya.binus.ac.id/login/index.php returns a link with a token. This change breaks Portal's log in mechanism. Some modification to AuthInteractor in Portal to handle this new login flow will be required to fix this.

**Comment by mstephen77** [comment]
Also, don't forget to change the form's action since it's no longer `sys_login.php`

**Comment by chrsep** [comment]
Thanks @mstephen77. Fix is now being rolled out.

**Comment by davidhonasan** [comment]
I still can't login with Portal. is it fixed yet? B21 here.

**Comment by chrsep** [comment]
@davidhonasan It's fixed on my side, I think binusmaya might have a problem a few hours ago, It should be fine now. Have you tried to update/signin again?

**Comment by davidhonasan** [comment]
i've tried to uninstall, clear data but still cant login it says , we have no idea whats wrong. but we have recieved the log. we'll look into this.

also sometimes it can weirdly logged on but it has weird agenda.

**Comment by davidhonasan** [comment]
correction, sometimes when it weirdly login. its show exam schedule.

**Comment by chrsep** [comment]
Does this also affects a lot of your friends?

**Comment by davidhonasan** [comment]
one of my friend also has this issue.

**Comment by Luche** [comment]
Strangely, it's saying bimay is sending weird data for me when I want to log in

**Comment by chrsep** [comment]
I've pushed an update, I'm not really sure yet why you guys is having this issue. I've make portal sign in call more frequent now, hopefully this fixes your issue. I'll look into this more later.

**Comment by davidhonasan** [comment]
i've updated to ver 0.5.0a. well sadly, this issue is still there. I'll put the video on here, so you can see what's happening in my device.
Hope that will help you on fixing this. Thanks.
https://youtu.be/y2oX3GLu4hU

**Comment by Luche** [comment]
Nvm, It's working. 
Yeay!

**Comment by chrsep** [comment]
@Luche Good to hear :smile: . @davidhonasan I experience similar issue with you just a few hours ago, some requests returns a PHP error instead of returning data, but now it seems to disappear, probably something about Binusmaya malfunctioning in my case. Were you experiencing this issue last week?

**Comment by davidhonasan** [comment]
lastweek before the login issues, my portal just fine, no issues. But now, Portal fetch only the exam schedule. There aren't any class schedule fetched by Portal.

**Comment by chrsep** [comment]
I'm going to close this old issue now, @davidhonasan sorry for my really late reply, but do you still experience this issue now? You can open a new issue if you do.
